# Generated by Django 4.2.3 on 2023-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default='False'),
        ),
    ]
