# Generated by Django 4.2.3 on 2023-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0004_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_id',
            field=models.IntegerField(default=0),
        ),
    ]
