# Generated by Django 4.2.3 on 2023-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0005_poll_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_id',
            field=models.IntegerField(default=1),
        ),
    ]
